/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ItemType = IDL.Variant({
  'salesReturn' : IDL.Null,
  'sale' : IDL.Null,
  'purchaseReturn' : IDL.Null,
  'purchase' : IDL.Null,
});
export const TransactionInput = IDL.Record({
  'customerName' : IDL.Opt(IDL.Text),
  'transactionCode' : IDL.Text,
  'transactionType' : ItemType,
  'metalPurity' : IDL.Opt(IDL.Float64),
  'code' : IDL.Text,
  'netWeight' : IDL.Float64,
  'cashBalance' : IDL.Opt(IDL.Float64),
  'timestamp' : IDL.Int,
  'quantity' : IDL.Nat,
  'stoneChargePerGram' : IDL.Opt(IDL.Float64),
  'metalBalance' : IDL.Opt(IDL.Float64),
});
export const JewelleryItem = IDL.Record({
  'code' : IDL.Text,
  'netWeight' : IDL.Float64,
  'isSold' : IDL.Bool,
  'pieces' : IDL.Nat,
  'grossWeight' : IDL.Float64,
  'itemType' : ItemType,
  'stoneWeight' : IDL.Float64,
});
export const TransactionRecord = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Opt(IDL.Text),
  'transactionCode' : IDL.Text,
  'transactionType' : ItemType,
  'metalPurity' : IDL.Opt(IDL.Float64),
  'netWeight' : IDL.Float64,
  'item' : JewelleryItem,
  'cashBalance' : IDL.Opt(IDL.Float64),
  'timestamp' : IDL.Int,
  'quantity' : IDL.Nat,
  'stoneChargePerGram' : IDL.Opt(IDL.Float64),
  'metalBalance' : IDL.Opt(IDL.Float64),
});
export const Customer = IDL.Record({
  'currentHoldings' : IDL.Vec(JewelleryItem),
  'name' : IDL.Text,
  'transactionHistory' : IDL.Vec(TransactionRecord),
});
export const TransactionAggregate = IDL.Record({
  'totalPieces' : IDL.Nat,
  'totalWeight' : IDL.Float64,
});
export const AnalyticsData = IDL.Record({
  'salesAggregate' : TransactionAggregate,
  'purchaseAggregate' : TransactionAggregate,
  'salesReturnAggregate' : TransactionAggregate,
  'purchaseReturnAggregate' : TransactionAggregate,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addBatchItems' : IDL.Func(
      [
        IDL.Vec(
          IDL.Tuple(
            IDL.Text,
            IDL.Float64,
            IDL.Float64,
            IDL.Float64,
            IDL.Nat,
            ItemType,
          )
        ),
      ],
      [],
      [],
    ),
  'addBatchTransactions' : IDL.Func(
      [IDL.Vec(TransactionInput)],
      [IDL.Vec(IDL.Text)],
      [],
    ),
  'addItem' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Float64, IDL.Float64, IDL.Nat, ItemType],
      [],
      [],
    ),
  'addTransaction' : IDL.Func(
      [
        IDL.Text,
        ItemType,
        IDL.Int,
        IDL.Opt(IDL.Text),
        IDL.Nat,
        IDL.Float64,
        IDL.Text,
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Float64),
      ],
      [IDL.Text],
      [],
    ),
  'createCustomer' : IDL.Func([IDL.Text], [], []),
  'deleteCustomer' : IDL.Func([IDL.Text], [], []),
  'getAllCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
  'getAllItems' : IDL.Func([], [IDL.Vec(JewelleryItem)], ['query']),
  'getAllTransactions' : IDL.Func([], [IDL.Vec(TransactionRecord)], ['query']),
  'getAvailableItemsByType' : IDL.Func(
      [ItemType],
      [IDL.Vec(JewelleryItem)],
      ['query'],
    ),
  'getCustomer' : IDL.Func([IDL.Text], [IDL.Opt(Customer)], ['query']),
  'getItem' : IDL.Func([IDL.Text], [IDL.Opt(JewelleryItem)], ['query']),
  'getTypeAggregates' : IDL.Func([], [AnalyticsData], ['query']),
  'renameCustomer' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'resetAllData' : IDL.Func([], [], []),
  'updateCustomer' : IDL.Func(
      [IDL.Text, TransactionRecord, JewelleryItem],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ItemType = IDL.Variant({
    'salesReturn' : IDL.Null,
    'sale' : IDL.Null,
    'purchaseReturn' : IDL.Null,
    'purchase' : IDL.Null,
  });
  const TransactionInput = IDL.Record({
    'customerName' : IDL.Opt(IDL.Text),
    'transactionCode' : IDL.Text,
    'transactionType' : ItemType,
    'metalPurity' : IDL.Opt(IDL.Float64),
    'code' : IDL.Text,
    'netWeight' : IDL.Float64,
    'cashBalance' : IDL.Opt(IDL.Float64),
    'timestamp' : IDL.Int,
    'quantity' : IDL.Nat,
    'stoneChargePerGram' : IDL.Opt(IDL.Float64),
    'metalBalance' : IDL.Opt(IDL.Float64),
  });
  const JewelleryItem = IDL.Record({
    'code' : IDL.Text,
    'netWeight' : IDL.Float64,
    'isSold' : IDL.Bool,
    'pieces' : IDL.Nat,
    'grossWeight' : IDL.Float64,
    'itemType' : ItemType,
    'stoneWeight' : IDL.Float64,
  });
  const TransactionRecord = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Opt(IDL.Text),
    'transactionCode' : IDL.Text,
    'transactionType' : ItemType,
    'metalPurity' : IDL.Opt(IDL.Float64),
    'netWeight' : IDL.Float64,
    'item' : JewelleryItem,
    'cashBalance' : IDL.Opt(IDL.Float64),
    'timestamp' : IDL.Int,
    'quantity' : IDL.Nat,
    'stoneChargePerGram' : IDL.Opt(IDL.Float64),
    'metalBalance' : IDL.Opt(IDL.Float64),
  });
  const Customer = IDL.Record({
    'currentHoldings' : IDL.Vec(JewelleryItem),
    'name' : IDL.Text,
    'transactionHistory' : IDL.Vec(TransactionRecord),
  });
  const TransactionAggregate = IDL.Record({
    'totalPieces' : IDL.Nat,
    'totalWeight' : IDL.Float64,
  });
  const AnalyticsData = IDL.Record({
    'salesAggregate' : TransactionAggregate,
    'purchaseAggregate' : TransactionAggregate,
    'salesReturnAggregate' : TransactionAggregate,
    'purchaseReturnAggregate' : TransactionAggregate,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addBatchItems' : IDL.Func(
        [
          IDL.Vec(
            IDL.Tuple(
              IDL.Text,
              IDL.Float64,
              IDL.Float64,
              IDL.Float64,
              IDL.Nat,
              ItemType,
            )
          ),
        ],
        [],
        [],
      ),
    'addBatchTransactions' : IDL.Func(
        [IDL.Vec(TransactionInput)],
        [IDL.Vec(IDL.Text)],
        [],
      ),
    'addItem' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Float64, IDL.Float64, IDL.Nat, ItemType],
        [],
        [],
      ),
    'addTransaction' : IDL.Func(
        [
          IDL.Text,
          ItemType,
          IDL.Int,
          IDL.Opt(IDL.Text),
          IDL.Nat,
          IDL.Float64,
          IDL.Text,
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Float64),
        ],
        [IDL.Text],
        [],
      ),
    'createCustomer' : IDL.Func([IDL.Text], [], []),
    'deleteCustomer' : IDL.Func([IDL.Text], [], []),
    'getAllCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
    'getAllItems' : IDL.Func([], [IDL.Vec(JewelleryItem)], ['query']),
    'getAllTransactions' : IDL.Func(
        [],
        [IDL.Vec(TransactionRecord)],
        ['query'],
      ),
    'getAvailableItemsByType' : IDL.Func(
        [ItemType],
        [IDL.Vec(JewelleryItem)],
        ['query'],
      ),
    'getCustomer' : IDL.Func([IDL.Text], [IDL.Opt(Customer)], ['query']),
    'getItem' : IDL.Func([IDL.Text], [IDL.Opt(JewelleryItem)], ['query']),
    'getTypeAggregates' : IDL.Func([], [AnalyticsData], ['query']),
    'renameCustomer' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'resetAllData' : IDL.Func([], [], []),
    'updateCustomer' : IDL.Func(
        [IDL.Text, TransactionRecord, JewelleryItem],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };