/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AnalyticsData {
  'salesAggregate' : TransactionAggregate,
  'purchaseAggregate' : TransactionAggregate,
  'salesReturnAggregate' : TransactionAggregate,
  'purchaseReturnAggregate' : TransactionAggregate,
}
export interface Customer {
  'currentHoldings' : Array<JewelleryItem>,
  'name' : string,
  'transactionHistory' : Array<TransactionRecord>,
}
export type ItemType = { 'salesReturn' : null } |
  { 'sale' : null } |
  { 'purchaseReturn' : null } |
  { 'purchase' : null };
export interface JewelleryItem {
  'code' : string,
  'netWeight' : number,
  'isSold' : boolean,
  'pieces' : bigint,
  'grossWeight' : number,
  'itemType' : ItemType,
  'stoneWeight' : number,
}
export interface TransactionAggregate {
  'totalPieces' : bigint,
  'totalWeight' : number,
}
export interface TransactionInput {
  'customerName' : [] | [string],
  'transactionCode' : string,
  'transactionType' : ItemType,
  'metalPurity' : [] | [number],
  'code' : string,
  'netWeight' : number,
  'grossWeight' : [] | [number],
  'cashBalance' : [] | [number],
  'timestamp' : bigint,
  'quantity' : bigint,
  'stoneWeight' : [] | [number],
  'stoneChargePerGram' : [] | [number],
  'metalBalance' : [] | [number],
}
export interface TransactionRecord {
  'id' : bigint,
  'customerName' : [] | [string],
  'transactionCode' : string,
  'transactionType' : ItemType,
  'metalPurity' : [] | [number],
  'netWeight' : number,
  'item' : JewelleryItem,
  'cashBalance' : [] | [number],
  'timestamp' : bigint,
  'quantity' : bigint,
  'stoneChargePerGram' : [] | [number],
  'metalBalance' : [] | [number],
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addBatchItems' : ActorMethod<
    [Array<[string, number, number, number, bigint, ItemType]>],
    undefined
  >,
  'addBatchTransactions' : ActorMethod<
    [Array<TransactionInput>],
    Array<string>
  >,
  'addItem' : ActorMethod<
    [string, number, number, number, bigint, ItemType],
    undefined
  >,
  'addTransaction' : ActorMethod<
    [
      string,
      ItemType,
      bigint,
      [] | [string],
      bigint,
      number,
      string,
      [] | [number],
      [] | [number],
      [] | [number],
      [] | [number],
      [] | [number],
      [] | [number],
    ],
    string
  >,
  'createCustomer' : ActorMethod<[string], undefined>,
  'deleteCustomer' : ActorMethod<[string], undefined>,
  'deleteSaleTransaction' : ActorMethod<[bigint], string>,
  'getAllCustomers' : ActorMethod<[], Array<Customer>>,
  'getAllItems' : ActorMethod<[], Array<JewelleryItem>>,
  'getAllTransactions' : ActorMethod<[], Array<TransactionRecord>>,
  'getAvailableItemsByType' : ActorMethod<[ItemType], Array<JewelleryItem>>,
  'getCustomer' : ActorMethod<[string], [] | [Customer]>,
  'getItem' : ActorMethod<[string], [] | [JewelleryItem]>,
  'getTypeAggregates' : ActorMethod<[], AnalyticsData>,
  'renameCustomer' : ActorMethod<[string, string], undefined>,
  'resetAllData' : ActorMethod<[], undefined>,
  'updateCustomer' : ActorMethod<
    [string, TransactionRecord, JewelleryItem],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];