/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface AnalyticsData {
    totalWeightSold: number;
    currentStockPieces: bigint;
    totalPurchaseReturnPieceCount: bigint;
    totalPurchaseReturnWeight: number;
    totalInventoryValue: number;
    salesReturnCount: bigint;
    salesTransactionCount: bigint;
    totalPiecesPurchased: bigint;
    totalSalesReturnWeight: number;
    currentStockNetWeight: number;
    totalSalesReturnPieceCount: bigint;
    numberOfPieces: bigint;
    purchaseCount: bigint;
    salesCount: bigint;
    purchaseReturnCount: bigint;
    totalWeightPurchased: number;
    totalPiecesSold: bigint;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface JewelleryItem {
    code: string;
    netWeight: number;
    isSold: boolean;
    pieces: bigint;
    grossWeight: number;
    itemType: ItemType;
    stoneWeight: number;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Customer {
    currentHoldings: Array<JewelleryItem>;
    name: string;
    transactionHistory: Array<TransactionRecord>;
}
export interface TransactionInput {
    customerName?: string;
    transactionCode: string;
    transactionType: ItemType;
    code: string;
    netWeight: number;
    timestamp: bigint;
    quantity: bigint;
}
export interface TransactionRecord {
    id: bigint;
    customerName?: string;
    transactionCode: string;
    transactionType: ItemType;
    netWeight: number;
    item: JewelleryItem;
    timestamp: bigint;
    quantity: bigint;
}
export enum ItemType {
    salesReturn = "salesReturn",
    sale = "sale",
    purchaseReturn = "purchaseReturn",
    purchase = "purchase"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    addBatchItems(itemsArray: Array<[string, number, number, number, bigint, ItemType]>): Promise<void>;
    addBatchTransactions(transactionsArray: Array<TransactionInput>): Promise<Array<string>>;
    addItem(code: string, grossWeight: number, stoneWeight: number, netWeight: number, pieces: bigint, itemType: ItemType): Promise<void>;
    addTransaction(code: string, transactionType: ItemType, timestamp: bigint, customerName: string | null, quantity: bigint, netWeight: number, transactionCode: string): Promise<string>;
    createCustomer(name: string): Promise<void>;
    deleteCustomer(name: string): Promise<void>;
    getAllCustomers(): Promise<Array<Customer>>;
    getAllItems(): Promise<Array<JewelleryItem>>;
    getAllTransactions(): Promise<Array<TransactionRecord>>;
    getAnalyticsData(): Promise<AnalyticsData>;
    getAvailableItemsByType(itemType: ItemType): Promise<Array<JewelleryItem>>;
    getCustomer(name: string): Promise<Customer | null>;
    getItem(code: string): Promise<JewelleryItem | null>;
    getTransaction(id: bigint): Promise<TransactionRecord | null>;
    getTransactionsByType(transactionType: ItemType): Promise<Array<TransactionRecord>>;
    updateCustomer(name: string, newTransaction: TransactionRecord, newItem: JewelleryItem): Promise<void>;
}
import type { Customer as _Customer, ItemType as _ItemType, JewelleryItem as _JewelleryItem, TransactionInput as _TransactionInput, TransactionRecord as _TransactionRecord, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async addBatchItems(arg0: Array<[string, number, number, number, bigint, ItemType]>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addBatchItems(to_candid_vec_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBatchItems(to_candid_vec_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addBatchTransactions(arg0: Array<TransactionInput>): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.addBatchTransactions(to_candid_vec_n12(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBatchTransactions(to_candid_vec_n12(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addItem(arg0: string, arg1: number, arg2: number, arg3: number, arg4: bigint, arg5: ItemType): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addItem(arg0, arg1, arg2, arg3, arg4, to_candid_ItemType_n10(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addItem(arg0, arg1, arg2, arg3, arg4, to_candid_ItemType_n10(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async addTransaction(arg0: string, arg1: ItemType, arg2: bigint, arg3: string | null, arg4: bigint, arg5: number, arg6: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addTransaction(arg0, to_candid_ItemType_n10(this._uploadFile, this._downloadFile, arg1), arg2, to_candid_opt_n15(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTransaction(arg0, to_candid_ItemType_n10(this._uploadFile, this._downloadFile, arg1), arg2, to_candid_opt_n15(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6);
            return result;
        }
    }
    async createCustomer(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createCustomer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCustomer(arg0);
            return result;
        }
    }
    async deleteCustomer(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCustomer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCustomer(arg0);
            return result;
        }
    }
    async getAllCustomers(): Promise<Array<Customer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCustomers();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCustomers();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllItems(): Promise<Array<JewelleryItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllItems();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllItems();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTransactions(): Promise<Array<TransactionRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTransactions();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTransactions();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAnalyticsData(): Promise<AnalyticsData> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnalyticsData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnalyticsData();
            return result;
        }
    }
    async getAvailableItemsByType(arg0: ItemType): Promise<Array<JewelleryItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableItemsByType(to_candid_ItemType_n10(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableItemsByType(to_candid_ItemType_n10(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomer(arg0: string): Promise<Customer | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomer(arg0);
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomer(arg0);
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getItem(arg0: string): Promise<JewelleryItem | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getItem(arg0);
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getItem(arg0);
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTransaction(arg0: bigint): Promise<TransactionRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransaction(arg0);
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransaction(arg0);
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTransactionsByType(arg0: ItemType): Promise<Array<TransactionRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactionsByType(to_candid_ItemType_n10(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactionsByType(to_candid_ItemType_n10(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateCustomer(arg0: string, arg1: TransactionRecord, arg2: JewelleryItem): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCustomer(arg0, to_candid_TransactionRecord_n31(this._uploadFile, this._downloadFile, arg1), to_candid_JewelleryItem_n33(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCustomer(arg0, to_candid_TransactionRecord_n31(this._uploadFile, this._downloadFile, arg1), to_candid_JewelleryItem_n33(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
}
function from_candid_Customer_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Customer): Customer {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_ItemType_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ItemType): ItemType {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_JewelleryItem_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JewelleryItem): JewelleryItem {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_TransactionRecord_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransactionRecord): TransactionRecord {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Customer]): Customer | null {
    return value.length === 0 ? null : from_candid_Customer_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_JewelleryItem]): JewelleryItem | null {
    return value.length === 0 ? null : from_candid_JewelleryItem_n20(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TransactionRecord]): TransactionRecord | null {
    return value.length === 0 ? null : from_candid_TransactionRecord_n25(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    currentHoldings: Array<_JewelleryItem>;
    name: string;
    transactionHistory: Array<_TransactionRecord>;
}): {
    currentHoldings: Array<JewelleryItem>;
    name: string;
    transactionHistory: Array<TransactionRecord>;
} {
    return {
        currentHoldings: from_candid_vec_n19(_uploadFile, _downloadFile, value.currentHoldings),
        name: value.name,
        transactionHistory: from_candid_vec_n24(_uploadFile, _downloadFile, value.transactionHistory)
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    code: string;
    netWeight: number;
    isSold: boolean;
    pieces: bigint;
    grossWeight: number;
    itemType: _ItemType;
    stoneWeight: number;
}): {
    code: string;
    netWeight: number;
    isSold: boolean;
    pieces: bigint;
    grossWeight: number;
    itemType: ItemType;
    stoneWeight: number;
} {
    return {
        code: value.code,
        netWeight: value.netWeight,
        isSold: value.isSold,
        pieces: value.pieces,
        grossWeight: value.grossWeight,
        itemType: from_candid_ItemType_n22(_uploadFile, _downloadFile, value.itemType),
        stoneWeight: value.stoneWeight
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    customerName: [] | [string];
    transactionCode: string;
    transactionType: _ItemType;
    netWeight: number;
    item: _JewelleryItem;
    timestamp: bigint;
    quantity: bigint;
}): {
    id: bigint;
    customerName?: string;
    transactionCode: string;
    transactionType: ItemType;
    netWeight: number;
    item: JewelleryItem;
    timestamp: bigint;
    quantity: bigint;
} {
    return {
        id: value.id,
        customerName: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.customerName)),
        transactionCode: value.transactionCode,
        transactionType: from_candid_ItemType_n22(_uploadFile, _downloadFile, value.transactionType),
        netWeight: value.netWeight,
        item: from_candid_JewelleryItem_n20(_uploadFile, _downloadFile, value.item),
        timestamp: value.timestamp,
        quantity: value.quantity
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    salesReturn: null;
} | {
    sale: null;
} | {
    purchaseReturn: null;
} | {
    purchase: null;
}): ItemType {
    return "salesReturn" in value ? ItemType.salesReturn : "sale" in value ? ItemType.sale : "purchaseReturn" in value ? ItemType.purchaseReturn : "purchase" in value ? ItemType.purchase : value;
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Customer>): Array<Customer> {
    return value.map((x)=>from_candid_Customer_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_JewelleryItem>): Array<JewelleryItem> {
    return value.map((x)=>from_candid_JewelleryItem_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TransactionRecord>): Array<TransactionRecord> {
    return value.map((x)=>from_candid_TransactionRecord_n25(_uploadFile, _downloadFile, x));
}
function to_candid_ItemType_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ItemType): _ItemType {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_JewelleryItem_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JewelleryItem): _JewelleryItem {
    return to_candid_record_n34(_uploadFile, _downloadFile, value);
}
function to_candid_TransactionInput_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionInput): _TransactionInput {
    return to_candid_record_n14(_uploadFile, _downloadFile, value);
}
function to_candid_TransactionRecord_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionRecord): _TransactionRecord {
    return to_candid_record_n32(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customerName?: string;
    transactionCode: string;
    transactionType: ItemType;
    code: string;
    netWeight: number;
    timestamp: bigint;
    quantity: bigint;
}): {
    customerName: [] | [string];
    transactionCode: string;
    transactionType: _ItemType;
    code: string;
    netWeight: number;
    timestamp: bigint;
    quantity: bigint;
} {
    return {
        customerName: value.customerName ? candid_some(value.customerName) : candid_none(),
        transactionCode: value.transactionCode,
        transactionType: to_candid_ItemType_n10(_uploadFile, _downloadFile, value.transactionType),
        code: value.code,
        netWeight: value.netWeight,
        timestamp: value.timestamp,
        quantity: value.quantity
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    customerName?: string;
    transactionCode: string;
    transactionType: ItemType;
    netWeight: number;
    item: JewelleryItem;
    timestamp: bigint;
    quantity: bigint;
}): {
    id: bigint;
    customerName: [] | [string];
    transactionCode: string;
    transactionType: _ItemType;
    netWeight: number;
    item: _JewelleryItem;
    timestamp: bigint;
    quantity: bigint;
} {
    return {
        id: value.id,
        customerName: value.customerName ? candid_some(value.customerName) : candid_none(),
        transactionCode: value.transactionCode,
        transactionType: to_candid_ItemType_n10(_uploadFile, _downloadFile, value.transactionType),
        netWeight: value.netWeight,
        item: to_candid_JewelleryItem_n33(_uploadFile, _downloadFile, value.item),
        timestamp: value.timestamp,
        quantity: value.quantity
    };
}
function to_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    code: string;
    netWeight: number;
    isSold: boolean;
    pieces: bigint;
    grossWeight: number;
    itemType: ItemType;
    stoneWeight: number;
}): {
    code: string;
    netWeight: number;
    isSold: boolean;
    pieces: bigint;
    grossWeight: number;
    itemType: _ItemType;
    stoneWeight: number;
} {
    return {
        code: value.code,
        netWeight: value.netWeight,
        isSold: value.isSold,
        pieces: value.pieces,
        grossWeight: value.grossWeight,
        itemType: to_candid_ItemType_n10(_uploadFile, _downloadFile, value.itemType),
        stoneWeight: value.stoneWeight
    };
}
function to_candid_tuple_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [string, number, number, number, bigint, ItemType]): [string, number, number, number, bigint, _ItemType] {
    return [
        value[0],
        value[1],
        value[2],
        value[3],
        value[4],
        to_candid_ItemType_n10(_uploadFile, _downloadFile, value[5])
    ];
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ItemType): {
    salesReturn: null;
} | {
    sale: null;
} | {
    purchaseReturn: null;
} | {
    purchase: null;
} {
    return value == ItemType.salesReturn ? {
        salesReturn: null
    } : value == ItemType.sale ? {
        sale: null
    } : value == ItemType.purchaseReturn ? {
        purchaseReturn: null
    } : value == ItemType.purchase ? {
        purchase: null
    } : value;
}
function to_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<TransactionInput>): Array<_TransactionInput> {
    return value.map((x)=>to_candid_TransactionInput_n13(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[string, number, number, number, bigint, ItemType]>): Array<[string, number, number, number, bigint, _ItemType]> {
    return value.map((x)=>to_candid_tuple_n9(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
